version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: mock-db
    restart: always
    environment:
      POSTGRES_USER: mockadmin
      POSTGRES_PASSWORD: mockpass
      POSTGRES_DB: mockdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  mock-manager:
    build: .
    container_name: mock-manager
    depends_on:
      - postgres
    restart: always
    environment:
      DATABASE_URL: postgres://mockadmin:mockpass@postgres:5432/mockdb
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    depends_on:
      - mock-manager
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
